name: GraalVM native-image

on:
  workflow_call:
    inputs:
      java_version:
        required: true
        type: string
        default: 17
      graalvm_version:
        required: true
        type: string
        default: 22.1.0
    outputs:
      artifact_name:
        description: Artifact name of native-image
        value: ${{ jobs.native_image.outputs.artifact_name }}

jobs:
  native_image:
    name: Test by GraalVM (${{ inputs.graalvm_version }}) / Java (${{ inputs.java_version }})
    runs-on: ubuntu-latest
    outputs:
      artifact_name: ${{ steps.output_artifact_name.outputs.name }}
    steps:
      - uses: actions/checkout@v2
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: ${{ inputs.java_version }}
          graalvm-version: ${{ inputs.graalvm_version }}
          native-image: true
      - name: Generate Executable
        run: mvn package -Dpackaging=docker-native -Dmicronaut.runtime=lambda -Pgraalvm
      - name: Set current datetime as env variable
        run: echo "CURRENT_DATETIME=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV
      - name: Set artifact name as env variable
        run: echo "ARTIFACT_NAME=lambda-native-image-${{ env.CURRENT_DATETIME }}" >> $GITHUB_ENV
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./target/function.zip
          retention-days: 7
      - id: output_artifact_name
        name: Set artifact name to output
        run: echo "::set-output name=name::${{ env.ARTIFACT_NAME }}"
